setting: &setting
  adapter: mysql2
  encoding: utf8
  user: root
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *setting
  database: toonmaxmedia_development

test:
  <<: *setting
  database: toonmaxmedia_test

production:
  <<: *setting
  database: toonmaxmedia_production
