setting: &setting
  adapter: mysql2
  encoding: utf8
  user: root
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *setting
  database: www_development

test:
  <<: *setting
  database: www_test

production:
  <<: *setting
  database: www_production
